# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='contracted',
            field=models.BooleanField(default=True),
        ),
    ]
