# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0003_tutor_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='contracted',
            field=models.BooleanField(default=False),
        ),
    ]
