# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0004_auto_20171025_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='contracted',
            field=models.BooleanField(default=True),
        ),
    ]
