# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0006_auto_20171025_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
