# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
        ('tutor_app', '0008_remove_tutor_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_slot', models.DateField(null=True)),
                ('time_of_slot', models.TimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='courses',
            field=models.ManyToManyField(null=True, to='course_app.Course'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='blocked_timeslots',
            field=models.ManyToManyField(null=True, to='tutor_app.Timeslot'),
        ),
    ]
