# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0010_auto_20171120_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subject_tag',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='university',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
