# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0011_auto_20171122_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='time_of_slot',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date_of_slot',
            field=models.DateTimeField(null=True),
        ),
    ]
