# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
        ('tutor_app', '0013_auto_20171122_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course_app.Course'),
        ),
    ]
