# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
        ('tutor_app', '0014_tutor_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='courses',
        ),
        migrations.AddField(
            model_name='tutor',
            name='course',
            field=models.ManyToManyField(to='course_app.Course'),
        ),
    ]
