# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
        ('tutor_app', '0017_review_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='average_rating',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='tutor',
            name='courses',
            field=models.ManyToManyField(to='course_app.Course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 24, 7, 14, 0, 472473)),
        ),
    ]
