# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0018_auto_20171124_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 24, 7, 15, 50, 466539)),
        ),
    ]
