# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0026_auto_20171124_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 24, 21, 58, 58, 232073)),
        ),
    ]
