# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 23:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0027_auto_20171124_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('pub_date', models.DateTimeField(null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_app.Tutor')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 24, 23, 31, 25, 910913)),
        ),
    ]
