# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 00:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0028_auto_20171124_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_t',
            name='desc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 25, 0, 23, 40, 535272)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject_tag',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
