# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_subject'),
        ('tutor_app', '0029_auto_20171125_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 25, 2, 8, 23, 397713)),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='subject_tag',
        ),
        migrations.AddField(
            model_name='tutor',
            name='subject_tag',
            field=models.ManyToManyField(to='course_app.Subject'),
        ),
    ]
