# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 02:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0030_auto_20171125_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 25, 2, 38, 51, 985255)),
        ),
    ]
