# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.Student'),
        ),
    ]
