# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10, null=True)),
                ('subject_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
