# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_auto_20171124_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
