# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myTutor_app', '0002_mytutor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('pub_date', models.DateTimeField()),
                ('mytutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTutor_app.myTutor')),
            ],
        ),
    ]
